### ISSUE TITLE
Fitting with damped oscillations💬 

### ISSUE THREAD

**Issue by jakubslawski** [glotaran/pyglotaran#1125]
Hello,
first, I would like to appreciate your work on pyglotaran - it's really great tool for the fitting of spectral data.
I'm trying to fit transient absorption 2D spectrum with 3-exponential decay + 3 damped oscillations. My model is:

> default_megacomplex: decay

dataset_groups:
  default:
    residual_function: variable_projection

dataset:
  PC_18nJ_mean:
    megacomplex: [mc_QD_PBS, damped_QD_PBS]
    initial_concentration: input_QD_PBS
    irf: irf_QD_PBS

megacomplex:
  mc_QD_PBS:
    k_matrix: [km_QD_PBS]
  damped_QD_PBS:
    type: damped-oscillation
    labels: [osc1, osc2, osc3]
    frequencies: [osc_QD_PBS.freq.1, osc_QD_PBS.freq.2, osc_QD_PBS.freq.3]
    rates: [osc_QD_PBS.rates.1, osc_QD_PBS.rates.2, osc_QD_PBS.rates.3] 

k_matrix:
  km_QD_PBS:
    matrix:
      (s2, s1): rates_QD_PBS.1
      (s3, s2): rates_QD_PBS.2
      (s3, s3): rates_QD_PBS.3

irf:
  irf_QD_PBS:
    type: spectral-gaussian
    center: irf_QD_PBS.center
    width: irf_QD_PBS.width

initial_concentration:
  input_QD_PBS:
    compartments: [s1, s2, s3]
    parameters: [
      input_QD_PBS.1,
      input_QD_PBS.0,
      input_QD_PBS.0,
      ]

**Comment by s-weigand** [comment]
@jakubslawski I wrapped your model in a [yaml markdown code block](https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/) for better readability 😉 

<pre>
```yaml
something: value
```
</pre>
renders as 

```yaml
something: value
```

Could be more specific about what your problem is?

**Comment by jakubslawski** [comment]
(sorry, I accidentally send the comment before I finished)
Hello,
first, I would like to appreciate your work on pyglotaran - it's really great tool for the fitting of spectral data.
I'm trying to fit transient absorption 2D spectrum with 3-exponential decay + 3 damped oscillations. My model is:

```
default_megacomplex: decay

dataset_groups:
  default:
    residual_function: variable_projection

dataset:
  PC_18nJ_mean:
    megacomplex: [mc_QD_PBS, damped_QD_PBS]
    initial_concentration: input_QD_PBS
    irf: irf_QD_PBS

megacomplex:
  mc_QD_PBS:
    k_matrix: [km_QD_PBS]
  damped_QD_PBS:
    type: damped-oscillation
    labels: [osc1, osc2, osc3]
    frequencies: [osc_QD_PBS.freq.1, osc_QD_PBS.freq.2, osc_QD_PBS.freq.3]
    rates: [osc_QD_PBS.rates.1, osc_QD_PBS.rates.2, osc_QD_PBS.rates.3] 

k_matrix:
  km_QD_PBS:
    matrix:
      (s2, s1): rates_QD_PBS.1
      (s3, s2): rates_QD_PBS.2
      (s3, s3): rates_QD_PBS.3

irf:
  irf_QD_PBS:
    type: spectral-gaussian
    center: irf_QD_PBS.center
    width: irf_QD_PBS.width

initial_concentration:
  input_QD_PBS:
    compartments: [s1, s2, s3]
    parameters: [
      input_QD_PBS.1,
      input_QD_PBS.0,
      input_QD_PBS.0,
      ] 
```
Fit converges but when I plot time traces with fitted curves and decays of individual components, it looks like the sum of components is smaller than fitted curve - the difference is equal 1 for each data point (see attached graph). There's not such a problem when the fit doesn't include damped oscillations but coherent-artifact megacomplex.
![fit](https://user-images.githubusercontent.com/79151400/188483305-cb2bd2bf-46ef-41fa-a888-f68d94eb70b2.png)

Maybe it's somehow related to time vectors for oscillations, they are vertically shifted from 0 to 1:
![time vectors](https://user-images.githubusercontent.com/79151400/188483717-7ec60ab1-8768-4b6e-8522-c26dce9b2107.png)


I would be grateful for any help.
