### ISSUE TITLE
[staging] 🐛 Add back per element A-/K-Matrices to result dataset

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#1498]
Currently staging saves the combined A-/K-Matrices for all decay elements.
If we need those is something to be decided by @ism200 .

However, what we need for validations are data variables on a per-element basis with the following name pattern

- `a_matrix_<element_name>`
- `k_matrix_<element_name>`
- `k_matrix_reduced_<element_name>`

To get rid of the spammy `xarray` warning:

```py
UserWarning: Duplicate dimension names present: dimensions {'species'} appear more than once in dims=('species', 'species').
```

Please use `('to_species', 'from_species')` notation.

### `main`
![image](https://github.com/user-attachments/assets/2a008550-3a73-47ab-8c71-fd5a9754ec07)
### `staging`
![image](https://github.com/user-attachments/assets/d91135bc-99d1-4769-847e-a79ca1d814c9)

**Comment by jsnel** [comment]
As discussed, please add the <element_name> suffix at the end.
`a_matrix_`<element_name>
`k_matrix_`<element_name>
rather than a element prefix.

Note element is new name for megacomplexes.

--

And in another example:
`decay_associated_amplitudes`_<element_name>
e.g.:
`decay_associated_amplitudes_mc1`
`decay_associated_amplitudes_mc2`

A special case is species_associated_amplitudes which we discussed is best to also save with the suffix, which before was only saved at a global level. But with the suffix in place it can then be consolidated later into the global amplitudes (spectra) for plotting purposes (in the extras).

**Comment by jsnel** [comment]
After experiencing the results in #1534 we decided on a small pivot, we're unflattening the results. 

Something along the lines:

```yaml
result
- data: dict (of Datasets)
- elements: dict of dicts (of Datasets of ElementResults) | None
  # using dataset attributes to 'type' ElementResults
- activations: ? (tbd)
- optimization properties : varied # can remain at top level, be at .optimization
```

Then, in the case of a kinetic element, at the level of
result.elements["dataset"]["element_name"] 

You just have
```
- species_associated_amplitudes
- kinetic_associated_amplitudes
- species_associated_concentrations
- k_matrix | k_matrix_full (or reduced, you know)
- a_matrix
```
