### ISSUE TITLE
Information is lost when saving a glotaran.analysis.result.Result object to file

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#322]
Currently a `glotaran.analysis.result.Result` class has a save method which stores a lot of output in a nc file, but quite a bit of information is lost in the process. Essentially only the data attribute is stored to file. 
-> Q: is one nc file stored for each dataset, or one nc file with an array of dataset?

Information that is lost in the process (not showing hidden attributes)

- [x] 'chisqr'
- [ ] 'covar'
- [x] 'initial_parameter'
- [x] 'model' -> see #317 
- [x] 'ndata'
- [x] 'nfev'
- [x] 'nfree'
- [ ] 'nnls'
- [x] 'nvars'
- [x] 'optimized_parameter'
- [x] 'red_chisqr'
- [x] 'root_mean_square_error' -> (sum of all datasets, rather than per dataset?)
- [x] 'scheme' (contains (duplicates?) of data, model, nfev, nnls, parameter (optimized?)
- [x] 'var_names'

**Comment by jsnel** [comment]
One way or another, we need a solution for storing all the information of an optimization in a self-contained manner, and one that allows you - being given those files - reconstruct the analysis scheme + inputs to the point where you can re-run the analysis on your end.

**Comment by joernweissenborn** [comment]
Bump

**Comment by s-weigand** [comment]
Currently if we save the result to `yaml` we get the following (DOAS example, since I had the folder open 😝  )
```yaml
number_of_function_evaluations: 1
success: true
termination_reason: The maximum number of function evaluations is exceeded.
glotaran_version: 0.6.0.dev0
free_parameter_labels:
  - irf.center
  - irf.disp1
  - irf.disp2
  - artifact.CAwidth
scheme: scheme.yml
initial_parameters: initial_parameters.csv
optimized_parameters: optimized_parameters.csv
parameter_history: parameter_history.csv
data:
  dataset1: dataset1.nc
chi_square: 16257.242851260951
degrees_of_freedom: 138297
number_of_data_points: 138301
number_of_jacobian_evaluations: 1
number_of_parameters: 4
optimality: 612782.8878031166
reduced_chi_square: 0.11755311287490655
root_mean_square_error: 0.342860194357564
```
